# Generated by Django 5.0.7 on 2024-09-14 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Language Assignment", max_length=200),
                ),
                (
                    "description",
                    models.TextField(default="This is a default description."),
                ),
                ("due_date", models.DateField(default="2024-08-26")),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "French"), ("es", "Spanish")],
                        default="fr",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(default="French Class", max_length=100)),
                (
                    "assignments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="class_codes",
                        to="transcription.assignment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="class_code",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_set",
                to="transcription.classcode",
            ),
        ),
        migrations.CreateModel(
            name="FlashcardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Basic Language Words", max_length=200),
                ),
                ("bulk_flashcards", models.TextField(blank=True, max_length=100000)),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "French"), ("es", "Spanish")],
                        default="fr",
                        max_length=2,
                    ),
                ),
                ("free_flow", models.BooleanField(default=False)),
                (
                    "class_code",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_sets_set",
                        to="transcription.classcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("french_word", models.TextField()),
                ("english_translation", models.TextField()),
                (
                    "flashcard_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="transcription.flashcardset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classcode",
            name="flashcard_sets",
            field=models.ManyToManyField(
                blank=True, related_name="class_codes", to="transcription.flashcardset"
            ),
        ),
        migrations.CreateModel(
            name="Game1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flashcard_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="transcription.flashcardset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(default="What is your name?")),
                ("expected_answer", models.TextField(default="My name is [NAME].")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="transcription.assignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserClassEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="transcription.classcode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "class_code")},
            },
        ),
        migrations.CreateModel(
            name="UserFlashcardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_flashcards", models.IntegerField(default=0)),
                ("completed_percentage", models.FloatField(default=0)),
                ("has_completed", models.BooleanField(default=False)),
                ("current_flashcard_index", models.IntegerField(default=0)),
                (
                    "flashcard_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.flashcardset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "flashcard_set")},
            },
        ),
        migrations.CreateModel(
            name="UserQuestionAttempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts_left", models.IntegerField(default=2)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "question")},
            },
        ),
        migrations.CreateModel(
            name="UserQuestionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_percentage", models.FloatField(default=0)),
                ("has_completed", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.assignment",
                    ),
                ),
                (
                    "completed_questions",
                    models.ManyToManyField(
                        related_name="completed_by_users", to="transcription.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "assignment")},
            },
        ),
    ]
