# Generated by Django 5.1.1 on 2024-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
