# Generated by Django 5.0.7 on 2024-09-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game1",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]

import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='transcription.FlashcardSet')),
            ],
        ),
    ]
