# Generated by Django 5.0.7 on 2024-08-20 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0002_assignment_classcode_flashcard_flashcardset_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
