# Generated by Django 5.0.7 on 2024-08-23 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0003_transcription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="classcode",
            name="flashcard_set",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_codes",
                to="transcription.flashcardset",
            ),
        ),
    ]
