# Generated by Django 5.0.7 on 2024-09-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0003_remove_old_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="language",
            field=models.CharField(
                choices=[("fr", "French"), ("es", "Spanish")],
                default="fr",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(default="Language Assignment", max_length=200),
        ),
    ]
