# Generated by Django 5.1.1 on 2024-09-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0003_alter_game1_id_gameparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameparticipant",
            name="sprite",
            field=models.CharField(
                choices=[
                    ("🐱", "Cat"),
                    ("🐶", "Dog"),
                    ("🐰", "Rabbit"),
                    ("🦊", "Fox"),
                    ("🦉", "Owl"),
                    ("🐼", "Panda"),
                    ("🐨", "Koala"),
                    ("🐯", "Tiger"),
                    ("🦁", "Lion"),
                    ("🐸", "Frog"),
                ],
                default="cat",
                max_length=20,
            ),
        ),
    ]
