# Generated by Django 5.1.1 on 2024-09-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0004_gameparticipant_sprite"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameparticipant",
            name="team",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
