# Generated by Django 5.0.7 on 2024-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0004_assignment_language_alter_assignment_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardset",
            name="language",
            field=models.CharField(
                choices=[("fr", "French"), ("es", "Spanish")],
                default="fr",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="english_translation",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="french_word",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="flashcardset",
            name="name",
            field=models.CharField(default="Basic Language Words", max_length=200),
        ),
    ]
