# Generated by Django 5.0.7 on 2024-08-23 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0005_userclassenrollment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userclassenrollment",
            name="enrolled_at",
        ),
        migrations.AlterField(
            model_name="classcode",
            name="flashcard_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_codes",
                to="transcription.flashcardset",
            ),
        ),
        migrations.AlterField(
            model_name="userclassenrollment",
            name="class_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_enrollments",
                to="transcription.classcode",
            ),
        ),
    ]
