# Generated by Django 5.0.7 on 2024-09-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0005_flashcardset_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardset",
            name="free_flow",
            field=models.BooleanField(default=False),
        ),
    ]
