# Generated by Django 5.1.1 on 2024-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0005_gameparticipant_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="game1",
            name="started",
            field=models.BooleanField(default=False),
        ),
    ]
