# Generated by Django 5.0.7 on 2024-09-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0006_flashcardset_free_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="class_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_set",
                to="transcription.classcode",
            ),
        ),
        migrations.AlterField(
            model_name="classcode",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="flashcardset",
            name="class_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcard_sets_set",
                to="transcription.classcode",
            ),
        ),
    ]
