# Generated by Django 5.0.7 on 2024-08-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0006_remove_userclassenrollment_enrolled_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classcode",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="classcode",
            name="flashcard_set",
        ),
        migrations.AddField(
            model_name="classcode",
            name="assignments",
            field=models.ManyToManyField(
                related_name="class_codes", to="transcription.assignment"
            ),
        ),
        migrations.AddField(
            model_name="classcode",
            name="flashcard_sets",
            field=models.ManyToManyField(
                related_name="class_codes", to="transcription.flashcardset"
            ),
        ),
    ]
