# Generated by Django 5.1.1 on 2024-09-16 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0006_game1_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="game1",
            name="assignments_created",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="GameAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_game", models.CharField(max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="transcription.game1",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_assignment",
                        to="transcription.gameparticipant",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "participant")},
            },
        ),
    ]
