# Generated by Django 5.1.1 on 2024-10-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0007_game1_assignments_created_gameassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameassignment",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
