# Generated by Django 5.0.7 on 2024-08-23 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0007_remove_classcode_assignment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userclassenrollment",
            name="flashcard_progress",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="UserFlashcardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_flashcards", models.IntegerField(default=0)),
                (
                    "flashcard_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.flashcardset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "flashcard_set")},
            },
        ),
    ]
