# Generated by Django 5.0.7 on 2024-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0008_interpersonalsession_interpersonalquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interpersonalquestion",
            name="transcription",
            field=models.TextField(
                blank=True, help_text="Transcription of the audio question"
            ),
        ),
    ]
