# Generated by Django 5.0.7 on 2024-08-25 00:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0008_userclassenrollment_flashcard_progress_and_more"),
    ]

    operations = []
