# Generated by Django 5.0.7 on 2024-09-22 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0009_interpersonalquestion_transcription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interpersonalsession",
            name="created_by",
        ),
    ]
