# Generated by Django 5.0.7 on 2024-08-25 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0009_auto_20240825_0020"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userflashcardprogress",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="classcode",
            name="assignments",
        ),
        migrations.RemoveField(
            model_name="classcode",
            name="flashcard_sets",
        ),
        migrations.RemoveField(
            model_name="flashcardset",
            name="bulk_flashcards",
        ),
        migrations.RemoveField(
            model_name="questionanswer",
            name="question",
        ),
        migrations.AlterUniqueTogether(
            name="userclassenrollment",
            unique_together={("user", "class_code")},
        ),
        migrations.AddField(
            model_name="assignment",
            name="class_code",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="transcription.classcode",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="description",
            field=models.TextField(default="This is a default description."),
        ),
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(default="2024-08-26"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="title",
            field=models.CharField(default="French Assignment", max_length=200),
        ),
        migrations.AddField(
            model_name="classcode",
            name="name",
            field=models.CharField(default="French Class", max_length=100),
        ),
        migrations.AddField(
            model_name="flashcardset",
            name="class_code",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcard_sets",
                to="transcription.classcode",
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="question_text",
            field=models.TextField(default="What is your name?"),
        ),
        migrations.AddField(
            model_name="userclassenrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="classcode",
            name="code",
            field=models.CharField(default="ABC1234567", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="english_translation",
            field=models.CharField(default="Hello", max_length=200),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="french_word",
            field=models.CharField(default="Bonjour", max_length=200),
        ),
        migrations.AlterField(
            model_name="flashcardset",
            name="name",
            field=models.CharField(default="Basic French Words", max_length=200),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="answer",
            field=models.TextField(default="My name is Jean."),
        ),
        migrations.AlterField(
            model_name="userclassenrollment",
            name="class_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="transcription.classcode",
            ),
        ),
        migrations.AlterField(
            model_name="userflashcardprogress",
            name="completed_flashcards",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userflashcardprogress",
            name="flashcard_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progress",
                to="transcription.flashcardset",
            ),
        ),
        migrations.AlterField(
            model_name="userflashcardprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcard_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Transcription",
        ),
        migrations.RemoveField(
            model_name="userclassenrollment",
            name="flashcard_progress",
        ),
    ]
