# Generated by Django 5.0.7 on 2024-09-23 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0010_remove_interpersonalsession_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentresponse",
            name="question",
        ),
        migrations.RemoveField(
            model_name="studentresponse",
            name="student",
        ),
        migrations.AlterField(
            model_name="interpersonalquestion",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to="interpersonal_questions/"
            ),
        ),
        migrations.CreateModel(
            name="UserInterpersonalProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_completed", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.interpersonalsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "session")},
            },
        ),
        migrations.DeleteModel(
            name="SessionCompletion",
        ),
        migrations.DeleteModel(
            name="StudentResponse",
        ),
    ]
