# Generated by Django 5.0.7 on 2024-08-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0010_alter_userflashcardprogress_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userflashcardprogress",
            name="has_completed",
            field=models.BooleanField(default=False),
        ),
    ]
