# Generated by Django 5.0.7 on 2024-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0011_userflashcardprogress_has_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardset",
            name="bulk_flashcards",
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
