# Generated by Django 5.1.2 on 2024-10-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0011_remove_studentresponse_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interpersonalquestion",
            name="transcription",
            field=models.TextField(blank=True),
        ),
    ]
