# Generated by Django 5.2.5 on 2025-08-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0012_alter_interpersonalquestion_transcription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interpersonalquestion",
            name="audio_file",
            field=models.URLField(max_length=500),
        ),
    ]
