# Generated by Django 5.0.7 on 2024-08-29 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0012_flashcardset_bulk_flashcards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classcode",
            name="assignments",
            field=models.ManyToManyField(
                blank=True, related_name="class_codes", to="transcription.assignment"
            ),
        ),
        migrations.AddField(
            model_name="classcode",
            name="flashcard_sets",
            field=models.ManyToManyField(
                blank=True, related_name="class_codes", to="transcription.flashcardset"
            ),
        ),
        migrations.AddField(
            model_name="userflashcardprogress",
            name="completed_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userflashcardprogress",
            name="current_flashcard_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="class_code",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_set",
                to="transcription.classcode",
            ),
        ),
        migrations.AlterField(
            model_name="flashcardset",
            name="class_code",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcard_sets_set",
                to="transcription.classcode",
            ),
        ),
        migrations.AlterField(
            model_name="userflashcardprogress",
            name="completed_flashcards",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userflashcardprogress",
            name="flashcard_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transcription.flashcardset",
            ),
        ),
        migrations.AlterField(
            model_name="userflashcardprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userflashcardprogress",
            unique_together={("user", "flashcard_set")},
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(default="What is your name?")),
                ("answer", models.TextField(default="My name is Jean.")),
                ("has_done", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="transcription.assignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserQuestionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_questions", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                ("completion_percentage", models.FloatField(default=0)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.assignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "assignment")},
            },
        ),
        migrations.DeleteModel(
            name="QuestionAnswer",
        ),
    ]
