# Generated by Django 5.0.7 on 2024-08-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0012_flashcardset_bulk_flashcards"),
    ]

    operations = [
        migrations.AddField(
            model_name="classcode",
            name="assignments",
            field=models.ManyToManyField(
                blank=True, related_name="class_codes", to="transcription.assignment"
            ),
        ),
        migrations.AddField(
            model_name="classcode",
            name="flashcard_sets",
            field=models.ManyToManyField(
                blank=True, related_name="class_codes", to="transcription.flashcardset"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="class_code",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_set",
                to="transcription.classcode",
            ),
        ),
        migrations.AlterField(
            model_name="flashcardset",
            name="class_code",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcard_sets_set",
                to="transcription.classcode",
            ),
        ),
    ]
