# Generated by Django 5.2.5 on 2025-08-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0013_alter_interpersonalquestion_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="interpersonalquestion",
            name="teacher_audio_file",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="interpersonalquestion",
            name="teacher_transcription",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="interpersonalquestion",
            name="audio_file",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
