# Generated by Django 5.0.7 on 2024-08-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcription",
            "0013_classcode_assignments_classcode_flashcard_sets_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="has_done",
        ),
        migrations.RemoveField(
            model_name="userquestionprogress",
            name="completion_percentage",
        ),
        migrations.RemoveField(
            model_name="userquestionprogress",
            name="total_questions",
        ),
        migrations.RemoveField(
            model_name="userquestionprogress",
            name="completed_questions",
        ),
        migrations.AddField(
            model_name="userquestionprogress",
            name="completed_questions",
            field=models.ManyToManyField(
                related_name="completed_by_users", to="transcription.question"
            ),
        ),
    ]
