# Generated by Django 5.0.7 on 2024-08-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcription",
            "0013_classcode_assignments_classcode_flashcard_sets_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userflashcardprogress",
            name="highest_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
