# Generated by Django 5.0.7 on 2024-08-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0014_remove_question_has_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionprogress",
            name="completed_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userquestionprogress",
            name="has_completed",
            field=models.BooleanField(default=False),
        ),
    ]
