# Generated by Django 5.0.7 on 2024-08-25 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0014_userflashcardprogress_highest_percentage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userflashcardprogress",
            name="highest_percentage",
        ),
        migrations.AddField(
            model_name="userflashcardprogress",
            name="completed_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userflashcardprogress",
            name="completed_flashcards",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userflashcardprogress",
            name="flashcard_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transcription.flashcardset",
            ),
        ),
        migrations.AlterField(
            model_name="userflashcardprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
