# Generated by Django 5.0.7 on 2025-08-23 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0014_interpersonalquestion_teacher_audio_file_and_more"),
        ("transcription", "0014_remove_bulk_questions_manual"),
    ]

    operations = []
