# Generated by Django 5.0.7 on 2024-09-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0015_userquestionprogress_completed_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
        migrations.AddField(
            model_name="question",
            name="expected_answer",
            field=models.TextField(default="My name is [NAME]."),
        ),
    ]
