# Generated by Django 5.0.7 on 2024-08-25 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcription",
            "0015_remove_userflashcardprogress_highest_percentage_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userflashcardprogress",
            unique_together={("user", "flashcard_set")},
        ),
    ]
