# Generated by Django 5.0.7 on 2024-08-25 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0016_alter_userflashcardprogress_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuestionAnswer",
            new_name="Question",
        ),
    ]
