# Generated by Django 5.0.7 on 2024-08-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0017_rename_questionanswer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="userflashcardprogress",
            name="current_flashcard_index",
            field=models.IntegerField(default=0),
        ),
    ]
