# Generated by Django 5.0.7 on 2024-08-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0018_userflashcardprogress_current_flashcard_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="has_done",
            field=models.BooleanField(default=False),
        ),
    ]
